import os
import sys

APP_NAME    = "OrbitSwipe"
APP_VERSION = "1.5.2"
CONFIG_VERSION = 3
CF = 0x08000000
APPDATA_DIR = os.path.join(os.environ.get("LOCALAPPDATA", os.path.expanduser("~")), APP_NAME)
CONFIG_FILE = os.path.join(APPDATA_DIR, "config.json")
LOG_FILE    = os.path.join(APPDATA_DIR, "crash.log")
LICENSE_FILE = os.path.join(APPDATA_DIR, "license.dat")
TRIAL_FILE   = os.path.join(APPDATA_DIR, "trial.dat")
LICENSE_URL  = "https://cross-tech-admin.vercel.app/api/validate"
TRIAL_DAYS = 30.0  # 30 day trial period
SYSTEM_DRIVE = os.environ.get("SystemDrive", "C:")

PACKAGES = [
    ("PyQt6",    "PyQt6"),
    ("Pillow",   "PIL"),
    ("pywin32",  "win32api"),
    ("psutil",   "psutil"),
    ("pycaw",    "pycaw"),
    ("comtypes", "comtypes"),
]

IS_FROZEN = getattr(sys, 'frozen', False)

ALL_TOOLS = [
    {"name": "Screenshot",  "icon": "📸",  "action": "screenshot"},
    {"name": "Volume +",    "icon": "🔊",  "action": "vol_up"},
    {"name": "Volume -",    "icon": "🔉",  "action": "vol_dn"},
    {"name": "Mute",        "icon": "🔇",  "action": "mute"},
    {"name": "Bright +",    "icon": "☀️",  "action": "br_up"},
    {"name": "Bright -",    "icon": "🌙",  "action": "br_dn"},
    {"name": "Task Mgr",    "icon": "📊",  "action": "taskmgr"},
    {"name": "Explorer",    "icon": "📁",  "action": "explorer"},
    {"name": "WinTop Manager", "icon": "🪟",  "action": "window_switcher"},
    {"name": "Vol Slider",  "icon": "🎚️",  "action": "vol_slider"},
    {"name": "Bri Slider",  "icon": "💡",  "action": "br_slider"},
    {"name": "Search",      "icon": "🔍",  "action": "search_bar"},
    {"name": "Settings",    "icon": "⚙️",  "action": "settings"},
    {"name": "Power Menu",  "icon": "⚡",  "action": "poweropts"},
    {"name": "Calculator",  "icon": "🧮",  "action": "calc"},
    {"name": "Notepad",     "icon": "📝",  "action": "notepad"},
    {"name": "Run Script",  "icon": "📜",  "action": "run_script"},
    {"name": "WiFi",        "icon": "📶",  "action": "wifi"},
    {"name": "Bluetooth",   "icon": "🔵",  "action": "bluetooth"},
    {"name": "Clipboard",   "icon": "📋",  "action": "clipboard"},
    {"name": "Command",     "icon": "💻",  "action": "cmd"},
    {"name": "Paint",       "icon": "🎨",  "action": "paint"},
    {"name": "Color Picker","icon": "💧",  "action": "colorpicker"},
    {"name": "Update",      "icon": "🔄",  "action": "update"},
    {"name": "App List",    "icon": "📦",  "action": "appwiz"},
    {"name": "Lock",        "icon": "🔒",  "action": "lock"},
    {"name": "Disk Clean",  "icon": "🧹",  "action": "cleanmgr"},
    {"name": "Display",     "icon": "📺",  "action": "display"},
    {"name": "Sound",       "icon": "🔈",  "action": "sound"},
    {"name": "Time Date",   "icon": "📅",  "action": "timedate"},
    {"name": "Net Connections", "icon": "🌐", "action": "ncpa"},
    {"name": "Firewall",    "icon": "🛡️",  "action": "firewall"},
    {"name": "Night Light", "icon": "🌙",  "action": "nightlight"},
    {"name": "Hotspot",     "icon": "🔥",  "action": "hotspot"},
    {"name": "Airplane",    "icon": "✈️",  "action": "airplane"},
    {"name": "Sys Info",    "icon": "ℹ️",  "action": "msinfo"},
    {"name": "Res Mon",     "icon": "📈",  "action": "resmon"},
    {"name": "Registry",    "icon": "🔑",  "action": "regedit"},
    {"name": "Disk Mgmt",   "icon": "💾",  "action": "diskmgmt"},
    {"name": "Dev Mgr",     "icon": "🛠️",  "action": "devmgmt"},
    {"name": "Services",    "icon": "⚙️",  "action": "services"},
    {"name": "Task Schd",   "icon": "📅",  "action": "taskschd"},
    {"name": "PowerShell",  "icon": "🐚",  "action": "powershell"},
    {"name": "DX Diag",     "icon": "🎮",  "action": "dxdiag"},
    {"name": "Sys Props",   "icon": "🖥️",  "action": "sysdm"},
    {"name": "Remote Desk", "icon": "🚪",  "action": "mstsc"},
    {"name": "Magnifier",   "icon": "🔍",  "action": "magnify"},
    {"name": "OSK",         "icon": "⌨️",  "action": "osk"},
    {"name": "Char Map",    "icon": "🔣",  "action": "charmap"},
    {"name": "Alarm",       "icon": "⏰",  "action": "alarm"},
    {"name": "Recorder",    "icon": "🎥",  "action": "recorder"},
    {"name": "Control Pnl", "icon": "🎛️",  "action": "control"},
    {"name": "Location",    "icon": "📍",  "action": "location"},
    {"name": "Rotation",    "icon": "🔄",  "action": "rotation"},
    {"name": "Ease Access", "icon": "♿",  "action": "accessibility"},
    {"name": "Energy Sav",  "icon": "🔋",  "action": "battery"},
    {"name": "Captions",    "icon": "💬",  "action": "captions"},
    {"name": "Cast",        "icon": "📺",  "action": "cast"},
    {"name": "Project",     "icon": "📽️",  "action": "project"},
    {"name": "Play/Pause",  "icon": "⏯",  "action": "music_toggle"},
    {"name": "Next Track",  "icon": "⏭",  "action": "music_next"},
    {"name": "Prev Track",  "icon": "⏮",  "action": "music_prev"},
    {"name": "Sleep",       "icon": "💤",  "action": "sleep"},
    {"name": "Hibernate",   "icon": "❄️",  "action": "hibernate"},
    {"name": "Restart",     "icon": "🔃",  "action": "restart"},
    {"name": "Shutdown",    "icon": "⏻",   "action": "shutdown"},
    {"name": "Awake Mode",  "icon": "☕",  "action": "awake"},
]

GLASS_PRESETS = {
    "Dark Obsidian": {"base_alpha": 115, "tint": (0,   0,   0),   "frost": 25, "blur": True},
    "Pure Crystal":  {"base_alpha": 35,  "tint": (200, 200, 240), "frost": 65, "blur": True},
    "Vibrant Glass": {"base_alpha": 75,  "tint": None,             "frost": 45, "blur": True},
    "Pure Ghost":    {"base_alpha": 0,   "tint": (0,   0,   0),   "frost": 0,  "blur": False},
    "Neon Night":    {"base_alpha": 140, "tint": (10,  10,  35),  "frost": 15, "blur": True},
    "Arctic Aura":   {"base_alpha": 55,  "tint": (180, 230, 255), "frost": 85, "blur": True},
    "Obsidian Sky":  {"base_alpha": 125, "tint": (25,  10,  45),  "frost": 30, "blur": True},
    "Emerald Mist":  {"base_alpha": 65,  "tint": (150, 255, 200), "frost": 60, "blur": True},
    "Dynamic Glass": {"base_alpha": 90,  "tint": "dynamic",        "frost": 40, "blur": True},
    "Custom Glass":  {"base_alpha": "custom", "tint": "custom",  "frost": "custom", "blur": "custom"},
}

DEFAULT_CFG = {
    "_cfg_version":   CONFIG_VERSION,
    "items":          [
        {"name": "Color Picker", "icon": "💧", "type": "tool", "action": "colorpicker"},
        {"name": "WinTop Manager", "icon": "🪟", "type": "tool", "action": "window_switcher"},
        {"name": "Search", "icon": "🔍", "type": "tool", "action": "search_bar"},
        {"type":"url","name":"OrbitSwipe","url":"https://orbitswipe.vercel.app/","icon":"🌐","icon_b64":""},
        {"type":"url","name":"GitHub","url":"https://github.com/mitul002/","icon":"🌐","icon_b64":""},
        {"type":"url","name":"YouTube","url":"https://www.youtube.com/@xpsplus3655","icon":"🌐","icon_b64":""},
    ],
    "recents":        [],
    "toolbox":        ALL_TOOLS[:33],
    "trigger_y":      0.45,
    "side":           "right",
    "radius":         230,
    "icon_size_inner": 42,
    "icon_size_outer": 48,
    "last_tab":       2,
    "theme_color":    "#4c1d95",
    "theme_color2":   "#7c3aed",
    "anim_k":         850,
    "blur_radius":    35,
    "glow_intensity": 1.0,
    "show_clock":     True,
    "show_stats":     True,
    "show_battery":   True,
    "show_network":   True,
    "music_mode":     "auto",
    "hotkey_enabled": True,
    "hotkey_mod":     "Alt",
    "hotkey_key":     "S",
    "hotkey_pin_mod": "Win+Alt",
    "hotkey_pin_key": "S",
    "hotkey_color_mod": "Win+Alt",
    "hotkey_color_key": "C",
    "slider_locked":  False,
    "sound_enabled":  True,
    "auto_hide":      False,
    "glass_preset":   "Dynamic Glass",
    "glass_custom_color": "#ffffff",
    "glass_custom_alpha": 100,
    "glass_custom_frost": 30,
    "glass_custom_blur":  35,
    "gradient_anim":  True,
    "independent_scroll": False,
    "scroll_sensitivity": 0.6,
    "custom_scripts": [],
    "music_show_vol": True,
    "music_show_viz": True,
    "main_style":     "dynamic",
    "enable_3d_glow": True,
}
